export const socketCommand = {
  None: 0,
  StartSafetyCheck: 1,
  StartUpdateFirmware: 2,
  StartSecurityCheck: 3,
  InitializeTestSequence: 4,
  ReceiveBooleanResponseForDeviceHasHeatingElement: 5,
  PerformRslMeasurement: 6,
  PerformRisoMeasurement: 7,
  PerformIdiffMeasurement: 8,
  PerformIprMeasurement_1: 9,
  PerformIprMeasurement_2: 10,
  PerformIprMeasurement_3: 11,
  PerformIprMeasurement_4: 12,
  PerformRltMeasurement: 13,
  PerformRSFMeasurement: 14,
  BuildMeasurementInfoXml: 15,
  CallEndSafetyTest: 16,
  VisualInspectionCheck: 17,
  FunctionTestCheck: 18,
  ReceiveBooleanResponseForMeasurementResult: 19,
  SaveMeasurementInfo: 20,
  StartService: 21,
  StartPreTestSequence1: 22,
};
