import { type HeadCell, type TableData } from '@/src/components/CustomTable/types';

export const data: TableData[] = [
  {
    Id: 1,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus: 'Short Circuit',
  },
  {
    Id: 2,
    Time: '9:00',
    Quarter: 'AD 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'B',
    Group: 97,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: false,
    NewOffer: true,
    LastUnitStatus: 'N/A',
  },
  {
    Id: 3,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus: 'Short Circuit',
  },
  {
    Id: 4,
    Time: '9:00',
    Quarter: 'AD 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'B',
    Group: 97,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: false,
    NewOffer: true,
    LastUnitStatus: 'N/A',
  },
  {
    Id: 5,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus: 'Short Circuit',
  },
  {
    Id: 6,
    Time: '9:00',
    Quarter: 'AD 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'B',
    Group: 97,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: false,
    NewOffer: true,
    LastUnitStatus: 'N/A',
  },
  {
    Id: 7,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus: 'Short Circuit',
  },
  {
    Id: 8,
    Time: '9:00',
    Quarter: 'AD 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'B',
    Group: 97,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: false,
    NewOffer: true,
    LastUnitStatus: 'N/A',
  },
  {
    Id: 9,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus: 'Short Circuit',
  },
  {
    Id: 10,
    Time: '9:00',
    Quarter: 'AD 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'B',
    Group: 97,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: false,
    NewOffer: true,
    LastUnitStatus: 'N/A',
  },
  {
    Id: 11,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus: 'Short Circuit',
  },
  {
    Id: 12,
    Time: '9:00',
    Quarter: 'AD 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'B',
    Group: 97,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: false,
    NewOffer: true,
    LastUnitStatus: 'N/A',
  },
  {
    Id: 13,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus:
      'Short CircuitShort CircuitShort CircuitShort CircuitShort CircuitShort CircuitShort CircuitShort CircuitShort CircuitShort Circuit',
  },
  {
    Id: 14,
    Time: '9:00',
    Quarter: 'AD 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'B',
    Group: 97,
    CustomerInformation:
      'Tom Hodgson, Egerkin road, Solothurn 4634, Egerkin road, Solothurn 4634, Egerkin road, Solothurn 4634,Egerkin road, Solothurn 4634 ,Egerkin road, Solothurn 4634 ,Egerkin road, Solothurn 4634',
    Offer: false,
    NewOffer: true,
    LastUnitStatus: 'N/A',
  },
  {
    Id: 15,
    Time: '8:00',
    Quarter: 'VO 09X',
    Text: '#282727272727 New Service order generated',
    Status: 'A',
    Group: 56,
    CustomerInformation: 'Tom Hodgson, Egerkin road, Solothurn 4634',
    Offer: true,
    NewOffer: true,
    LastUnitStatus: 'Short Circuit',
  },
];

export const headCells: HeadCell[] = [
  {
    id: 'Time',
    label: 'Time',
    sortable: true,
  },
  {
    id: 'Quarter',
    label: 'Quarter',
    sortable: true,
  },
  {
    id: 'Text',
    label: 'Text',
    sortable: true,
  },
  {
    id: 'Status',
    label: 'Status',
    sortable: true,
  },
  {
    id: 'Group',
    label: 'Group',
    sortable: true,
  },
  {
    id: 'CustomerInformation',
    label: 'Customer Information',
    sortable: true,
  },
  {
    id: 'Offer',
    label: 'Offer',
    sortable: false,
    align: 'center',
  },
  {
    id: 'NewOffer',
    label: 'New Offer',
    sortable: false,
    align: 'center',
  },
  {
    id: 'LastUnitStatus',
    label: 'Last Unit Status',
    sortable: true,
  },
];
