export const emptyTourData = {
  TimeEntities: [],
  SyncDate: '',
  SyncMessage: null,
  TechnicianLogs: [],
  SamOrders: [],
  WorkflowDetails: [],
  ServiceOrderLocations: [],
  ServiceOrderOverviews: [],
  ApartmentDetails: [],
  ServiceOrderDetails: [],
  SamKvs: [],
  SamKvDetails: [],
  SamKvTimeFrames: [],
  ServiceOrderKVs: [],
  SamOffers: [],
  SamOfferDetails: [],
  SamOfferProductDetails: [],
  TimberOrders: [],
  TimberOrderDetails: [],
  TimberOrderDetailPictures: [],
  InvoiceDetails: [],
  ManagementCompanies: [],
  ServiceOrderManagementCompanies: [],
  ServiceOrderComplaints: [],
  ServiceOrderComplaintDetails: [],
  PersonnelEfforts: [],
  ClientSettings: [],
  BranchDetails: [],
  ManagementMediations: [],
  AccompaniedTechnicians: [],
  UsersSamOrders: [],
  Offers: [],
  AppointmentTypes: [],
  Appointments: [],
  AppointmentHistories: [],
  AdditionalSales: [],
  DeviceDetails: [],
  ServiceOrderDeviceInspections: [],
  QrCodeDetails: [],
  ProductQuantityOnOrders: [],
};

export const emptyTourDataModel = () => {
  return emptyTourData;
};
